apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base
  - ingress.yaml

patches:
  - path: patches/deployment-patch.yaml

configMapGenerator:
  - name: demo-api-config
    literals:
      - log-level=debug

generators:
  - ksops-generator.yaml

images:
  - name: 649822034735.dkr.ecr.eu-west-1.amazonaws.com/k8s-platform/demo-api
    newTag: dev-latest
