apiVersion: v1
kind: Secret
metadata:
    name: demo-api-db
    namespace: dev
stringData:
    url: ENC[AES256_GCM,data:/4u7aWAt4tzIQmszi7+CrfBuCfavLSvj1XmqWjlS3yzqll0NEezFu8Z7CJWUF2p2CX2vAfR9CGaGwKz6o6X8OIGLWQOvYYriIoFRIXgmb1Qf5T3BobwZpnaLSl8dsdkvTYSGdBuOtcw1lIx5MahcZu36hrka4tPJchWme446dt3aKPVPsRaPKJeLxP93Qs651lFZGh8mudybXdA/UOopXCk=,iv:bq0/7nMYNBUkxdhFu4hSRG71oiUxpVDAyRSablbTnes=,tag:EklTD7SqKoxPdeOsZvVdrQ==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    kms:
        - arn: arn:aws:kms:eu-west-1:649822034735:alias/k8s-platform-sops
          aws_profile: ""
          created_at: "2026-06-22T15:02:23Z"
          enc: AQICAHgJLDDJihMR9ev0M5+m+LfZNMfy6mh8PPnoyL7YsrGrRAEuPhjSEEkZXqGK2GCE7cFAAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMI8Szu84R9i2QLAWQAgEQgDvyOanxUYsHrrYrtdrqx5utfetee6LpZWv6epVSxQPSL+GfxlhgVStsj9DVX5UvBbK4lZGE3CRwbazWXA==
    lastmodified: "2026-06-22T15:02:24Z"
    mac: ENC[AES256_GCM,data:w+kfMendu/tG3XvIMIarAzqg8U3/CWy3538NwjkGBdlaOeksD0Zu8kIsrD51wEUM6l+xaUJvMV6nwe/IIKoBLUOQIkmGBKMHVxhJV073xaemzGeR8W0h6vhHOiFSPMdjiW+UYgPIu+bx2CLRZ99RdqSmPLvtOQNNOmM+F0PMv9s=,iv:p1AsW8YO30g4IncfBMI3SUf816IHxM7jmjh9LmgUwXY=,tag:C+/BMv6hidNE9BcRXQ/qyg==,type:str]
    version: 3.13.1
