apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::649822034735:role/k8s-platform-demo-api-irsa
automountServiceAccountToken: false
