controller:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  admissionWebhooks:
    enabled: true

  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"

  nodeSelector:
    node-role: platform

  tolerations:
    - key: node-role
      value: platform
      effect: NoSchedule

  priorityClassName: platform-critical
