apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: patches/deployment-patch.yaml

images:
  - name: ACCOUNT_ID.dkr.ecr.eu-west-1.amazonaws.com/k8s-platform/demo-api
    newTag: prod-latest
