apiVersion: v1
kind: Secret
metadata:
    name: demo-api-db
    namespace: prod
stringData:
    url: ENC[AES256_GCM,data:D4+YrOW7kF6GNVlv50LqcJx3GCMYfr/L07LPymoO5Zf8xZDGkQUVvPIlE+vAsmDbpKz/BNwgV4YjkekVbLPVLDQPjXHZg+on0jlBbs/3P67UTOMJ4cmHQuqCEUbyXiKEKnwh+QcOrlmYjAWZxmvGM11RWI4JSUr306tQGQmnOpIYlqjT9fk6VkabF8fa3lpclVisyz+0MhLo4UerqF/1YzE=,iv:99W2GF4t1wYzOYjT9oVcdn+bB9SGa8pD/xj8JP3i23w=,tag:Q7e0o/DxYqndfSZIGUkr2g==,type:str]
sops:
    encrypted_regex: ^(data|stringData)$
    kms:
        - arn: arn:aws:kms:eu-west-1:649822034735:alias/k8s-platform-sops
          aws_profile: ""
          created_at: "2026-06-22T15:02:24Z"
          enc: AQICAHgJLDDJihMR9ev0M5+m+LfZNMfy6mh8PPnoyL7YsrGrRAHjxoo9ePZYODZb9e8g/zO/AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMjmIgfI8sk8TObujKAgEQgDsDPyKAIIUnmoyFbX/t5ayoA4wMVN+p/jtItOkH7jDOAz9TvdEnrrMUBNEDey3HA0mc6NvEitMUFUuyYQ==
    lastmodified: "2026-06-22T15:02:24Z"
    mac: ENC[AES256_GCM,data:j0a0GDPTr6w6KME44HL5DjfBeGkblzAa3fMyp9eoT7hM4zzcrtLddz398Eg5Q5SVEpPmhFvR36lsf3zVGBOP2y2O+49Ifq6/DJtE/Ze2b6pZQs3HWGbdwDaq29VAooZvJH6qCj8xjnNhYo8Jh8MC9C5aBxcCF+v8YljoXXFFUeE=,iv:SFwOCVMRA4W4P8K4pSSodWCgV0SxqxsNh+iDivAJt5g=,tag:AG39F5q6p8zPAKvcgd0uIg==,type:str]
    version: 3.13.1
