name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

concurrency:
  group: terraform-apply
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-1
  TF_WORKING_DIR: terraform/environments/dev

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production
    env:
      TF_IN_AUTOMATION: "true"
      TF_INPUT: "false"
      TF_VAR_db_password: ${{ secrets.TF_VAR_DB_PASSWORD }}
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ~1.15

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan

      - name: Terraform Apply
        run: terraform apply tfplan
